#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""tools/doc_gen - API 文档生成器。

从 SV 源码头注释与公共符号（package/class/function/task/typedef/enum）生成
Markdown API 文档，输出到 docs/api/<file>.md。

用法：
  python3 tools/doc_gen/doc_gen.py                # 生成全部
  python3 tools/doc_gen/doc_gen.py --dry-run      # 只打印，不写文件
"""

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from common import repo_path, walk_sv_files, scan_public_symbols, extract_header, report, main_or_fail  # noqa: E402

OUT_DIR = repo_path("docs", "api")


def render_md(sv_file, sv_text, syms):
    """生成单个文件的 Markdown。"""
    lines = []
    lines.append(f"# API - `{sv_file}`")
    lines.append("")
    header = extract_header(sv_text)
    if header:
        lines.append("## 概述")
        lines.append("")
        for h in header.splitlines():
            lines.append(h.lstrip("/").strip() if h.lstrip().startswith("//") else h)
        lines.append("")
    lines.append("## 公共符号")
    lines.append("")
    lines.append("| 类别 | 符号 |")
    lines.append("|---|---|")
    for kind in ("packages", "classes", "functions", "tasks", "typedefs", "enums"):
        for name in syms[kind]:
            lines.append(f"| {kind} | `{name}` |")
    lines.append("")
    lines.append("---")
    lines.append(f"_Generated by `tools/doc_gen/doc_gen.py`._")
    lines.append("")
    return "\n".join(lines)


def run():
    dry = "--dry-run" in sys.argv
    os.makedirs(OUT_DIR, exist_ok=True)
    n = 0
    for f in walk_sv_files(("src", "rtl")):
        p = repo_path(f)
        with open(p, "r", encoding="utf-8") as fh:
            text = fh.read()
        syms = scan_public_symbols(text)
        if not any(syms.values()):
            continue  # 无公共符号则不生成
        md = render_md(f, text, syms)
        out_name = os.path.join(OUT_DIR, f.replace("/", "__") + ".md")
        if dry:
            print(f"[DRY] would write {os.path.relpath(out_name, repo_path())} ({len(md)} bytes)")
        else:
            with open(out_name, "w", encoding="utf-8") as fh:
                fh.write(md)
        n += 1
    report(True, f"doc_gen: generated {n} API docs into docs/api/")
    return True


if __name__ == "__main__":
    main_or_fail(run)
